BEGIN;

CREATE EXTENSION IF NOT EXISTS vector;

CREATE EXTENSION IF NOT EXISTS pg_trgm;

CREATE EXTENSION IF NOT EXISTS unaccent;

CREATE TABLE admin_account (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username TEXT NOT NULL UNIQUE,
    password_hash TEXT NOT NULL,
    session_token_hash TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE audit_log (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    admin_id BIGINT NOT NULL REFERENCES admin_account(id),
    action TEXT NOT NULL,
    target_type TEXT NOT NULL,
    target_id BIGINT NOT NULL,
    detail JSONB,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX idx_audit_log_admin_created ON audit_log (admin_id, created_at DESC);

CREATE INDEX idx_audit_log_target ON audit_log (target_type, target_id);

CREATE TABLE document (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title TEXT NOT NULL,
    source_url TEXT,
    source_type TEXT NOT NULL,
    content_hash TEXT NOT NULL,
    language_code TEXT,
    published_at DATE,
    accessed_at TIMESTAMPTZ,
    rights_note TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT chk_document_source_type CHECK (
        source_type IN (
            'official',
            'academic',
            'management',
            'press',
            'encyclopedia',
            'archive',
            'book',
            'other'
        )
    ),
    CONSTRAINT uq_document_source_version UNIQUE (source_url, content_hash)
);

CREATE TABLE passage (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    document_id BIGINT NOT NULL REFERENCES document(id) ON DELETE CASCADE,
    passage_index INT NOT NULL,
    text TEXT NOT NULL,
    embedding VECTOR(1024),
    tsv TSVECTOR GENERATED ALWAYS AS (
        to_tsvector('simple', text)
    ) STORED,
    page_number INT,
    location_note TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT chk_passage_index CHECK (passage_index >= 0),
    CONSTRAINT uq_passage_document_index UNIQUE (document_id, passage_index)
);

CREATE INDEX idx_passage_document ON passage (document_id);
CREATE INDEX idx_passage_tsv ON passage USING GIN (tsv);
CREATE INDEX idx_passage_text_trgm ON passage USING GIN (text gin_trgm_ops);
CREATE INDEX idx_passage_embedding
    ON passage USING HNSW (embedding vector_cosine_ops)
    WHERE embedding IS NOT NULL;

CREATE TABLE entity (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    type TEXT NOT NULL,
    canonical_name TEXT NOT NULL,
    normalized_name TEXT NOT NULL,
    subtype TEXT,
    in_scope BOOLEAN NOT NULL DEFAULT true,
    entry_status TEXT NOT NULL DEFAULT 'draft',
    depth_tier SMALLINT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT chk_entity_type CHECK (
        type IN ('person', 'place', 'event', 'artifact')
    ),
    CONSTRAINT chk_entity_entry_status CHECK (
        entry_status IN ('draft', 'reviewed', 'published', 'archived')
    ),
    CONSTRAINT chk_entity_depth_tier CHECK (
        depth_tier IS NULL OR depth_tier >= 0
    ),
    CONSTRAINT uq_entity_normalized_type UNIQUE (normalized_name, type)
);

CREATE INDEX idx_entity_name_trgm
    ON entity USING GIN (canonical_name gin_trgm_ops);
CREATE INDEX idx_entity_normalized_name ON entity (normalized_name);
CREATE INDEX idx_entity_scope_status_depth
    ON entity (in_scope, entry_status, depth_tier);
CREATE INDEX idx_entity_type ON entity (type);

CREATE TABLE entity_alias (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    entity_id BIGINT NOT NULL REFERENCES entity(id) ON DELETE CASCADE,
    alias TEXT NOT NULL,
    normalized_alias TEXT NOT NULL,
    language_code TEXT,
    source_passage_id BIGINT REFERENCES passage(id) ON DELETE SET NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT uq_entity_alias_normalized UNIQUE (entity_id, normalized_alias)
);

CREATE INDEX idx_entity_alias_normalized ON entity_alias (normalized_alias);
CREATE INDEX idx_entity_alias_trgm
    ON entity_alias USING GIN (alias gin_trgm_ops);

CREATE TABLE entity_external_id (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    entity_id BIGINT NOT NULL REFERENCES entity(id) ON DELETE CASCADE,
    provider TEXT NOT NULL,
    external_id TEXT NOT NULL,
    url TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT uq_entity_external_provider_id UNIQUE (provider, external_id),
    CONSTRAINT uq_entity_provider UNIQUE (entity_id, provider)
);

CREATE TABLE place_profile (
    entity_id BIGINT PRIMARY KEY REFERENCES entity(id) ON DELETE CASCADE,
    address TEXT,
    ward TEXT,
    district TEXT,
    province TEXT,
    latitude NUMERIC(9, 6),
    longitude NUMERIC(9, 6),
    primary_passage_id BIGINT REFERENCES passage(id) ON DELETE SET NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT chk_place_profile_latitude CHECK (
        latitude IS NULL OR latitude BETWEEN -90 AND 90
    ),
    CONSTRAINT chk_place_profile_longitude CHECK (
        longitude IS NULL OR longitude BETWEEN -180 AND 180
    )
);

CREATE TABLE claim_field (
    code TEXT PRIMARY KEY,
    label_vi TEXT NOT NULL,
    label_en TEXT
);

CREATE TABLE claim (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    entity_id BIGINT NOT NULL REFERENCES entity(id) ON DELETE CASCADE,
    field_code TEXT NOT NULL REFERENCES claim_field(code),
    value JSONB NOT NULL,
    status TEXT NOT NULL DEFAULT 'proposed',
    confidence NUMERIC(4, 3),
    note TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT chk_claim_status CHECK (
        status IN ('proposed', 'accepted', 'disputed', 'rejected', 'superseded')
    ),
    CONSTRAINT chk_claim_confidence CHECK (
        confidence IS NULL OR confidence BETWEEN 0 AND 1
    )
);

CREATE INDEX idx_claim_entity_field ON claim (entity_id, field_code);
CREATE INDEX idx_claim_value_gin ON claim USING GIN (value);

CREATE TABLE claim_evidence (
    claim_id BIGINT NOT NULL REFERENCES claim(id) ON DELETE CASCADE,
    passage_id BIGINT NOT NULL REFERENCES passage(id) ON DELETE CASCADE,
    stance TEXT NOT NULL DEFAULT 'supports',
    note TEXT,
    CONSTRAINT chk_claim_evidence_stance CHECK (
        stance IN ('supports', 'contradicts', 'context')
    ),
    PRIMARY KEY (claim_id, passage_id)
);

CREATE TABLE predicate (
    code TEXT PRIMARY KEY,
    label_vi TEXT NOT NULL,
    label_en TEXT,
    inverse_of TEXT REFERENCES predicate(code),
    is_symmetric BOOLEAN NOT NULL DEFAULT false
);

CREATE TABLE relation (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    subject_id BIGINT NOT NULL REFERENCES entity(id) ON DELETE CASCADE,
    predicate TEXT NOT NULL REFERENCES predicate(code),
    object_id BIGINT NOT NULL REFERENCES entity(id) ON DELETE CASCADE,
    status TEXT NOT NULL DEFAULT 'proposed',
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT chk_relation_no_loop CHECK (subject_id <> object_id),
    CONSTRAINT chk_relation_status CHECK (
        status IN ('proposed', 'accepted', 'disputed', 'rejected', 'superseded')
    )
);

CREATE INDEX idx_relation_subject ON relation (subject_id, predicate);
CREATE INDEX idx_relation_object ON relation (object_id, predicate);

CREATE TABLE relation_evidence (
    relation_id BIGINT NOT NULL REFERENCES relation(id) ON DELETE CASCADE,
    passage_id BIGINT NOT NULL REFERENCES passage(id) ON DELETE CASCADE,
    stance TEXT NOT NULL DEFAULT 'supports',
    note TEXT,
    CONSTRAINT chk_relation_evidence_stance CHECK (
        stance IN ('supports', 'contradicts', 'context')
    ),
    PRIMARY KEY (relation_id, passage_id)
);

CREATE TABLE event_type (
    code TEXT PRIMARY KEY,
    label_vi TEXT NOT NULL,
    label_en TEXT
);

CREATE TABLE timeline_event (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    entity_id BIGINT NOT NULL REFERENCES entity(id) ON DELETE CASCADE,
    year_start INT NOT NULL,
    year_end INT,
    precision TEXT NOT NULL DEFAULT 'year',
    event_type TEXT NOT NULL REFERENCES event_type(code),
    title TEXT NOT NULL,
    summary TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT chk_timeline_year_range CHECK (
        year_end IS NULL OR year_end >= year_start
    ),
    CONSTRAINT chk_timeline_precision CHECK (
        precision IN ('year', 'decade', 'century', 'range', 'circa')
    )
);

CREATE INDEX idx_timeline_entity_year
    ON timeline_event (entity_id, year_start);

CREATE TABLE timeline_event_evidence (
    timeline_event_id BIGINT NOT NULL
        REFERENCES timeline_event(id) ON DELETE CASCADE,
    passage_id BIGINT NOT NULL REFERENCES passage(id) ON DELETE CASCADE,
    stance TEXT NOT NULL DEFAULT 'supports',
    CONSTRAINT chk_timeline_evidence_stance CHECK (
        stance IN ('supports', 'contradicts', 'context')
    ),
    PRIMARY KEY (timeline_event_id, passage_id)
);

CREATE TABLE participant_role (
    code TEXT PRIMARY KEY,
    label_vi TEXT NOT NULL,
    label_en TEXT
);

CREATE TABLE timeline_event_participant (
    timeline_event_id BIGINT NOT NULL
        REFERENCES timeline_event(id) ON DELETE CASCADE,
    entity_id BIGINT NOT NULL REFERENCES entity(id) ON DELETE CASCADE,
    role_code TEXT NOT NULL REFERENCES participant_role(code),
    PRIMARY KEY (timeline_event_id, entity_id, role_code)
);

CREATE INDEX idx_timeline_participant_entity
    ON timeline_event_participant (entity_id, role_code);

CREATE TABLE narrative_section (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    entity_id BIGINT NOT NULL REFERENCES entity(id) ON DELETE CASCADE,
    section_code TEXT NOT NULL,
    title TEXT NOT NULL,
    body_md TEXT NOT NULL,
    language_code TEXT NOT NULL DEFAULT 'vi',
    order_index INT NOT NULL DEFAULT 0,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT chk_narrative_section_code CHECK (
        section_code IN (
            'tong_quan',
            'ten_goi',
            'khoi_lap',
            'vai_tro_lich_su',
            'kien_truc',
            'hien_vat',
            'nhan_vat',
            'bien_dong_hien_dai',
            'tham_quan'
        )
    ),
    CONSTRAINT uq_narrative_section
        UNIQUE (entity_id, section_code, language_code)
);

CREATE TABLE narrative_section_evidence (
    narrative_section_id BIGINT NOT NULL
        REFERENCES narrative_section(id) ON DELETE CASCADE,
    passage_id BIGINT NOT NULL REFERENCES passage(id) ON DELETE CASCADE,
    PRIMARY KEY (narrative_section_id, passage_id)
);

CREATE INDEX idx_narrative_entity ON narrative_section (entity_id, order_index);

CREATE INDEX idx_narrative_entity ON narrative_section (entity_id, order_index);

CREATE TABLE site (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    region TEXT NOT NULL,
    entity_id BIGINT NOT NULL REFERENCES entity(id),
    description TEXT,
    source_passage_id BIGINT REFERENCES passage(id) ON DELETE
    SET
        NULL,
        created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
        CONSTRAINT uq_site_entity UNIQUE (entity_id)
);

CREATE TABLE scene (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    site_id BIGINT NOT NULL REFERENCES site(id) ON DELETE CASCADE,
    name TEXT NOT NULL,
    transform_7dof JSONB NOT NULL,
    order_index INT NOT NULL DEFAULT 0,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT uq_scene_site_name UNIQUE (site_id, name)
);

CREATE INDEX idx_scene_site_order ON scene (site_id, order_index);

CREATE TABLE model_asset (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    scene_id BIGINT NOT NULL REFERENCES scene(id) ON DELETE CASCADE,
    lod_level INT NOT NULL,
    file_url TEXT NOT NULL,
    format TEXT NOT NULL DEFAULT 'glb',
    compression TEXT,
    file_size_bytes BIGINT,
    is_proxy BOOLEAN NOT NULL DEFAULT false,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT chk_model_asset_lod CHECK (lod_level >= 0),
    CONSTRAINT chk_model_asset_format CHECK (
        format IN (
            'glb',
            'splat',
            'sog'
        )
    ),
    CONSTRAINT chk_model_asset_compression CHECK (
        compression IS NULL
        OR compression IN (
            'draco',
            'ktx2',
            'meshopt',
            'draco+ktx2',
            'none'
        )
    ),
    CONSTRAINT chk_model_asset_size CHECK (
        file_size_bytes IS NULL
        OR file_size_bytes >= 0
    ),
    CONSTRAINT uq_model_asset_scene_lod UNIQUE (scene_id, lod_level)
);

CREATE TABLE story (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    site_id BIGINT NOT NULL REFERENCES site(id) ON DELETE CASCADE,
    title TEXT NOT NULL,
    camera_path JSONB NOT NULL,
    created_by BIGINT REFERENCES admin_account(id) ON DELETE
    SET
        NULL,
        created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX idx_story_site ON story (site_id);

CREATE TABLE narration (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    story_id BIGINT NOT NULL UNIQUE REFERENCES story(id) ON DELETE CASCADE,
    audio_path TEXT NOT NULL,
    duration_ms INT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT chk_narration_duration CHECK (duration_ms >= 0)
);

CREATE TABLE transcript (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    story_id BIGINT NOT NULL REFERENCES story(id) ON DELETE CASCADE,
    text TEXT NOT NULL,
    start_ms INT NOT NULL,
    end_ms INT NOT NULL,
    seq INT NOT NULL,
    CONSTRAINT chk_transcript_time CHECK (
        start_ms >= 0
        AND end_ms >= start_ms
    ),
    CONSTRAINT chk_transcript_seq CHECK (seq >= 0),
    CONSTRAINT uq_transcript_story_seq UNIQUE (story_id, seq)
);

CREATE INDEX idx_transcript_story_time ON transcript (story_id, start_ms);

CREATE TABLE hotspot (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    scene_id BIGINT NOT NULL REFERENCES scene(id) ON DELETE CASCADE,
    entity_id BIGINT NOT NULL REFERENCES entity(id) ON DELETE CASCADE,
    x DOUBLE PRECISION NOT NULL,
    y DOUBLE PRECISION NOT NULL,
    z DOUBLE PRECISION NOT NULL,
    label TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX idx_hotspot_scene ON hotspot (scene_id);

CREATE INDEX idx_hotspot_entity ON hotspot (entity_id);

CREATE TABLE chat_session (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ip_hash TEXT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX idx_chat_session_created ON chat_session (created_at DESC);

CREATE TABLE chat_message (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_id BIGINT NOT NULL REFERENCES chat_session(id) ON DELETE CASCADE,
    role TEXT NOT NULL,
    content TEXT NOT NULL,
    citations JSONB NOT NULL DEFAULT '[]' :: jsonb,
    response_status TEXT,
    abstained BOOLEAN NOT NULL DEFAULT false,
    retrieval_strategy TEXT,
    latency_ms INT,
    model TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT chk_chat_message_role CHECK (
        role IN (
            'user',
            'assistant'
        )
    ),
    CONSTRAINT chk_chat_message_citations_array CHECK (
        jsonb_typeof(citations) = 'array'
    ),
    CONSTRAINT chk_chat_message_response CHECK (
        (
            role = 'user'
            AND response_status IS NULL
            AND abstained = false
        )
        OR (
            role = 'assistant'
            AND response_status IN (
                'answered',
                'clarify',
                'abstained'
            )
            AND abstained = (response_status = 'abstained')
        )
    ),
    CONSTRAINT chk_chat_message_latency CHECK (
        latency_ms IS NULL
        OR latency_ms >= 0
    )
);

CREATE INDEX idx_chat_message_session ON chat_message (session_id, created_at);

CREATE TABLE chat_message_evidence (
    message_id BIGINT NOT NULL REFERENCES chat_message(id) ON DELETE CASCADE,
    passage_id BIGINT NOT NULL REFERENCES passage(id) ON DELETE RESTRICT,
    citation_label TEXT NOT NULL,
    evidence_type TEXT NOT NULL,
    retrieval_score REAL,
    reason TEXT,
    PRIMARY KEY (message_id, passage_id),
    CONSTRAINT uq_chat_message_citation_label UNIQUE (message_id, citation_label),
    CONSTRAINT chk_chat_evidence_score CHECK (
        retrieval_score IS NULL
        OR retrieval_score BETWEEN 0
        AND 1
    )
);

CREATE INDEX idx_chat_message_evidence_message ON chat_message_evidence (message_id);

CREATE INDEX idx_chat_message_evidence_passage ON chat_message_evidence (passage_id);

CREATE FUNCTION enforce_chat_answer_evidence() RETURNS TRIGGER LANGUAGE plpgsql AS $ $ DECLARE target_message_id BIGINT;

BEGIN IF TG_TABLE_NAME = 'chat_message_evidence' THEN IF TG_OP = 'DELETE' THEN target_message_id := OLD.message_id;

ELSE target_message_id := NEW.message_id;

END IF;

ELSE IF TG_OP = 'DELETE' THEN target_message_id := OLD.id;

ELSE target_message_id := NEW.id;

END IF;

END IF;

IF EXISTS (
    SELECT
        1
    FROM
        chat_message
    WHERE
        id = target_message_id
        AND role = 'assistant'
        AND response_status = 'answered'
)
AND NOT EXISTS (
    SELECT
        1
    FROM
        chat_message_evidence
    WHERE
        message_id = target_message_id
) THEN RAISE EXCEPTION 'answered chat message % requires at least one evidence passage',
target_message_id USING ERRCODE = '23514';

END IF;

IF TG_OP = 'DELETE' THEN RETURN OLD;

END IF;

RETURN NEW;

END;

$ $;

CREATE CONSTRAINT TRIGGER trg_chat_answer_requires_evidence
AFTER
INSERT
    OR
UPDATE
    ON chat_message DEFERRABLE INITIALLY DEFERRED FOR EACH ROW EXECUTE FUNCTION enforce_chat_answer_evidence();

CREATE CONSTRAINT TRIGGER trg_chat_evidence_cannot_orphan_answer
AFTER
    DELETE
    OR
UPDATE
    ON chat_message_evidence DEFERRABLE INITIALLY DEFERRED FOR EACH ROW EXECUTE FUNCTION enforce_chat_answer_evidence();

CREATE TABLE chat_feedback (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    message_id BIGINT NOT NULL REFERENCES chat_message(id) ON DELETE CASCADE,
    rating SMALLINT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT chk_chat_feedback_rating CHECK (rating IN (-1, 1))
);

CREATE INDEX idx_chat_feedback_message ON chat_feedback (message_id);

CREATE FUNCTION set_updated_at() RETURNS TRIGGER LANGUAGE plpgsql AS $ $ BEGIN NEW.updated_at = now();

RETURN NEW;

END;

$ $;

CREATE TRIGGER trg_entity_updated_at BEFORE
UPDATE
    ON entity FOR EACH ROW EXECUTE FUNCTION set_updated_at();

CREATE TRIGGER trg_place_profile_updated_at BEFORE
UPDATE
    ON place_profile FOR EACH ROW EXECUTE FUNCTION set_updated_at();

CREATE TRIGGER trg_narrative_updated_at BEFORE
UPDATE
    ON narrative_section FOR EACH ROW EXECUTE FUNCTION set_updated_at();

INSERT INTO
    claim_field (
        code,
        label_vi,
        value_type,
        default_unit,
        is_time_sensitive
    )
VALUES
    (
        'construction_year',
        'Năm xây dựng / khởi lập',
        'year',
        NULL,
        false
    ),
    (
        'completion_year',
        'Năm hoàn thành',
        'year',
        NULL,
        false
    ),
    (
        'height',
        'Chiều cao',
        'number',
        'm',
        false
    ),
    (
        'address',
        'Địa chỉ',
        'text',
        NULL,
        true
    ),
    (
        'description',
        'Mô tả',
        'text',
        NULL,
        false
    );

INSERT INTO
    event_type (code, label_vi, label_en)
VALUES
    ('establishment', 'Khởi lập', 'Establishment'),
    ('construction', 'Xây dựng', 'Construction'),
    ('restoration', 'Trùng tu', 'Restoration'),
    ('renovation', 'Tu sửa', 'Renovation'),
    (
        'historical',
        'Sự kiện lịch sử',
        'Historical Event'
    ),
    (
        'political',
        'Sự kiện chính trị',
        'Political Event'
    ),
    (
        'religious',
        'Sự kiện tôn giáo',
        'Religious Event'
    ),
    ('cultural', 'Sự kiện văn hóa', 'Cultural Event'),
    ('other', 'Khác', 'Other');

INSERT INTO
    predicate (
        code,
        label_vi,
        label_en,
        is_symmetric
    )
VALUES
    ('founded', 'khởi lập', 'founded', false),
    ('located_in', 'nằm tại', 'located in', false),
    (
        'built_by',
        'được xây dựng bởi',
        'built by',
        false
    ),
    (
        'restored_by',
        'được trùng tu bởi',
        'restored by',
        false
    ),
    (
        'designed_by',
        'được thiết kế bởi',
        'designed by',
        false
    ),
    (
        'associated_with',
        'liên quan đến',
        'associated with',
        true
    ),
    ('part_of', 'thuộc về', 'part of', false),
    ('contains', 'chứa', 'contains', false),
    (
        'commemorates',
        'tưởng niệm',
        'commemorates',
        false
    );

COMMIT;