CREATE EXTENSION IF NOT EXISTS vector;
CREATE EXTENSION IF NOT EXISTS pg_trgm;
CREATE EXTENSION IF NOT EXISTS unaccent;

-- ADMIN / AUDIT
CREATE TABLE admin_account (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username TEXT NOT NULL UNIQUE,
    password_hash TEXT NOT NULL,
    session_token_hash TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE audit_log (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    admin_id BIGINT NOT NULL REFERENCES admin_account(id),
    action TEXT NOT NULL,
    target_type TEXT NOT NULL,
    target_id BIGINT NOT NULL,
    detail JSONB,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX idx_audit_log_admin_created ON audit_log (admin_id, created_at DESC);
CREATE INDEX idx_audit_log_target ON audit_log (target_type, target_id);



CREATE TABLE passage (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    passage_index INT NOT NULL,
    text TEXT NOT NULL,
    embedding VECTOR(1024),
    page_number INT,
    location_note TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT chk_passage_index CHECK (passage_index >= 0)
);

CREATE INDEX idx_passage_text_trgm
    ON passage USING GIN (text gin_trgm_ops);

CREATE INDEX idx_passage_embedding
    ON passage USING HNSW (embedding vector_cosine_ops)
    WHERE embedding IS NOT NULL;


-- HERITAGE / 3D TOUR
CREATE TABLE language (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code TEXT NOT NULL UNIQUE,
    name TEXT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);


INSERT INTO language (code, name)
VALUES
    ('en', 'English'),
    ('vi', 'Vietnamese')
ON CONFLICT (code) DO NOTHING;


CREATE TABLE heritage (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    -- Basic information
    slug TEXT NOT NULL UNIQUE,
    title TEXT NOT NULL,
    tagline TEXT,
    headline TEXT,
    description TEXT,
    region TEXT,
    lat DOUBLE PRECISION,
    lng DOUBLE PRECISION,
    map_zoom DOUBLE PRECISION,
    display_map BOOLEAN NOT NULL DEFAULT TRUE,
    duration_seconds INT,
    launch_date DATE,
    publish_state TEXT NOT NULL DEFAULT 'draft',
    publish_date DATE,
    card_image_url TEXT,
    splash_image_url TEXT,
    hover_video_url TEXT,
    language1_id BIGINT REFERENCES language(id) ON DELETE SET NULL,
    language2_id BIGINT REFERENCES language(id) ON DELETE SET NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);


CREATE TABLE sky_preset (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL UNIQUE,
    turbidity DOUBLE PRECISION,
    rayleigh DOUBLE PRECISION,
    elevation DOUBLE PRECISION,
    azimuth DOUBLE PRECISION,
    exposure DOUBLE PRECISION,
    light_settings JSONB,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE scene (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    heritage_id BIGINT NOT NULL REFERENCES heritage(id) ON DELETE CASCADE,
    sequence INT NOT NULL,
    title TEXT NOT NULL,
    description TEXT,
    sky_preset_id BIGINT REFERENCES sky_preset(id) ON DELETE SET NULL,
    -- Camera nằm trong GLB (NULL = dùng camera mặc định của GLB)
    camera_node_name TEXT,
    -- Hoặc khai báo camera trực tiếp trong DB
    cam_start_pos JSONB,
    cam_start_target JSONB,
    cam_zoom_pos JSONB,
    cam_zoom_target JSONB,
    instant_move BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT uq_scene_heritage_sequence UNIQUE (heritage_id, sequence),
    CONSTRAINT chk_scene_sequence CHECK (sequence >= 0)
);

CREATE INDEX idx_scene_heritage_sequence ON scene (heritage_id, sequence);

CREATE TABLE model_asset (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    scene_id BIGINT NOT NULL REFERENCES scene(id) ON DELETE CASCADE,
    file_url TEXT NOT NULL,
    format TEXT NOT NULL DEFAULT 'glb',
    lod_level INT NOT NULL DEFAULT 0,
    compression TEXT,
    file_size_bytes BIGINT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT chk_model_asset_format CHECK (format IN ('glb', 'splat', 'sog')),
    CONSTRAINT chk_model_asset_lod CHECK (lod_level >= 0),
    CONSTRAINT chk_model_asset_compression CHECK (
        compression IS NULL
        OR compression IN ('draco', 'ktx2', 'meshopt', 'draco+ktx2', 'none')
    ),
    CONSTRAINT chk_model_asset_file_size CHECK (
        file_size_bytes IS NULL OR file_size_bytes >= 0
    ),
    CONSTRAINT uq_model_asset_scene_lod UNIQUE (scene_id, lod_level)
);

CREATE INDEX idx_model_asset_scene ON model_asset (scene_id);

CREATE TABLE voice (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    title TEXT,
    bio TEXT,
    headshot_url TEXT,
    intro_video_url TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE heritage_voice (
    heritage_id BIGINT NOT NULL
        REFERENCES heritage(id) ON DELETE CASCADE,

    voice_id BIGINT NOT NULL
        REFERENCES voice(id) ON DELETE CASCADE,

    sort_order INT NOT NULL DEFAULT 0,

    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),

    PRIMARY KEY (heritage_id, voice_id),

    CONSTRAINT chk_heritage_voice_sort_order
        CHECK (sort_order >= 0)
);

CREATE INDEX idx_heritage_voice_order
    ON heritage_voice (heritage_id, sort_order);

CREATE TABLE voice_clip (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    voice_id BIGINT NOT NULL REFERENCES voice(id) ON DELETE CASCADE,
    scene_id BIGINT NOT NULL REFERENCES scene(id) ON DELETE CASCADE,
    video_url TEXT,
    audio_url TEXT,
    bubble_text TEXT,
    sort_order INT NOT NULL DEFAULT 0,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT chk_voice_clip_sort_order CHECK (sort_order >= 0)
);

CREATE INDEX idx_voice_clip_scene_order ON voice_clip (scene_id, sort_order);
CREATE INDEX idx_voice_clip_voice ON voice_clip (voice_id);

CREATE TABLE media_item (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    scene_id BIGINT NOT NULL REFERENCES scene(id) ON DELETE CASCADE,
    type TEXT NOT NULL,
    title TEXT,
    caption TEXT,
    asset_url TEXT NOT NULL,
    thumb_url TEXT,
    credit TEXT,
    sort_order INT NOT NULL DEFAULT 0,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT chk_media_item_type CHECK (
        type IN ('image', 'video', 'audio', 'model', 'document', 'other')
    ),
    CONSTRAINT chk_media_item_sort_order CHECK (sort_order >= 0)
);

CREATE INDEX idx_media_item_scene_order ON media_item (scene_id, sort_order);

CREATE TABLE interactive (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    scene_id BIGINT NOT NULL REFERENCES scene(id) ON DELETE CASCADE,
    mode TEXT NOT NULL,
    cam_pos JSONB,
    cam_target JSONB,
    explore_area JSONB,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT uq_interactive_scene_mode UNIQUE (scene_id, mode)
);

CREATE INDEX idx_interactive_scene ON interactive (scene_id);

CREATE TABLE interactive_highlight (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    interactive_id BIGINT NOT NULL REFERENCES interactive(id) ON DELETE CASCADE,
    popup_title TEXT,
    popup_text TEXT,
    media_url TEXT,
    cam_pos JSONB,
    cam_target JSONB,
    lens_pos JSONB,
    lens_rot JSONB,
    lens_scale JSONB,
    sort_order INT NOT NULL DEFAULT 0,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT chk_interactive_highlight_sort_order CHECK (sort_order >= 0)
);

CREATE INDEX idx_interactive_highlight_order
    ON interactive_highlight (interactive_id, sort_order);

CREATE TABLE scene_highlight (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    scene_id BIGINT NOT NULL REFERENCES scene(id) ON DELETE CASCADE,
    model_url TEXT NOT NULL,
    position JSONB NOT NULL,
    rotation JSONB NOT NULL,
    scale JSONB NOT NULL,
    animation_type TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX idx_scene_highlight_scene ON scene_highlight (scene_id);



CREATE TABLE link (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    heritage_id BIGINT NOT NULL REFERENCES heritage(id) ON DELETE CASCADE,
    language_id BIGINT REFERENCES language(id) ON DELETE SET NULL,
    title TEXT NOT NULL,
    url TEXT NOT NULL,
    link_type TEXT,
    sort_order INT NOT NULL DEFAULT 0,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT chk_link_sort_order CHECK (sort_order >= 0)
);

CREATE INDEX idx_link_heritage_order ON link (heritage_id, sort_order);

-- =====================================================================
-- CHAT
-- =====================================================================
CREATE TABLE chat_session (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ip_hash TEXT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX idx_chat_session_created ON chat_session (created_at DESC);

CREATE TABLE chat_message (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_id BIGINT NOT NULL REFERENCES chat_session(id) ON DELETE CASCADE,
    role TEXT NOT NULL,
    content TEXT NOT NULL,
    citations JSONB NOT NULL DEFAULT '[]'::jsonb,
    response_status TEXT,
    abstained BOOLEAN NOT NULL DEFAULT false,
    retrieval_strategy TEXT,
    latency_ms INT,
    model TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT chk_chat_message_role CHECK (role IN ('user', 'assistant')),
    CONSTRAINT chk_chat_message_citations_array CHECK (jsonb_typeof(citations) = 'array'),
    CONSTRAINT chk_chat_message_response CHECK (
        (
            role = 'user'
            AND response_status IS NULL
            AND abstained = false
        )
        OR (
            role = 'assistant'
            AND response_status IN ('answered', 'clarify', 'abstained')
            AND abstained = (response_status = 'abstained')
        )
    ),
    CONSTRAINT chk_chat_message_latency CHECK (latency_ms IS NULL OR latency_ms >= 0)
);

CREATE INDEX idx_chat_message_session ON chat_message (session_id, created_at);

CREATE TABLE chat_feedback (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    message_id BIGINT NOT NULL REFERENCES chat_message(id) ON DELETE CASCADE,
    rating SMALLINT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT chk_chat_feedback_rating CHECK (rating IN (-1, 1))
);

CREATE INDEX idx_chat_feedback_message ON chat_feedback (message_id);
