CREATE EXTENSION IF NOT EXISTS vector;
CREATE EXTENSION IF NOT EXISTS pg_trgm;
CREATE EXTENSION IF NOT EXISTS unaccent;

-- ADMIN / AUDIT
CREATE TABLE admin_account (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username TEXT NOT NULL UNIQUE,
    password_hash TEXT NOT NULL,
    session_token_hash TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE audit_log (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    admin_id BIGINT NOT NULL REFERENCES admin_account(id),
    action TEXT NOT NULL,
    target_type TEXT NOT NULL,
    target_id BIGINT NOT NULL,
    detail JSONB,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX idx_audit_log_admin_created ON audit_log (admin_id, created_at DESC);
CREATE INDEX idx_audit_log_target ON audit_log (target_type, target_id);

-- DOCUMENT / PASSAGE (RAG)
CREATE TABLE document (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title TEXT NOT NULL,
    source_url TEXT,
    source_type TEXT NOT NULL,
    content_hash TEXT NOT NULL,
    language_code TEXT,
    published_at DATE,
    accessed_at TIMESTAMPTZ,
    rights_note TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT chk_document_source_type CHECK (
        source_type IN (
            'official', 'academic', 'management', 'press',
            'encyclopedia', 'archive', 'book', 'other'
        )
    ),
    CONSTRAINT uq_document_source_version UNIQUE (source_url, content_hash)
);

CREATE TABLE passage (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    document_id BIGINT NOT NULL REFERENCES document(id) ON DELETE CASCADE,
    passage_index INT NOT NULL,
    text TEXT NOT NULL,
    embedding VECTOR(1024),
    tsv TSVECTOR GENERATED ALWAYS AS (to_tsvector('simple', text)) STORED,
    page_number INT,
    location_note TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT chk_passage_index CHECK (passage_index >= 0),
    CONSTRAINT uq_passage_document_index UNIQUE (document_id, passage_index)
);

CREATE INDEX idx_passage_document ON passage (document_id);
CREATE INDEX idx_passage_tsv ON passage USING GIN (tsv);
CREATE INDEX idx_passage_text_trgm ON passage USING GIN (text gin_trgm_ops);
CREATE INDEX idx_passage_embedding
    ON passage USING HNSW (embedding vector_cosine_ops)
    WHERE embedding IS NOT NULL;

-- ENTITY
CREATE TABLE entity (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    type TEXT NOT NULL,
    canonical_name TEXT NOT NULL,
    normalized_name TEXT NOT NULL,
    subtype TEXT,
    in_scope BOOLEAN NOT NULL DEFAULT true,
    entry_status TEXT NOT NULL DEFAULT 'draft',
    depth_tier SMALLINT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT chk_entity_type CHECK (
        type IN ('person', 'place', 'event', 'artifact')
    ),
    CONSTRAINT chk_entity_entry_status CHECK (
        entry_status IN ('draft', 'reviewed', 'published', 'archived')
    ),
    CONSTRAINT chk_entity_depth_tier CHECK (
        depth_tier IS NULL OR depth_tier >= 0
    ),
    CONSTRAINT uq_entity_normalized_type UNIQUE (normalized_name, type)
);

CREATE INDEX idx_entity_name_trgm ON entity USING GIN (canonical_name gin_trgm_ops);
CREATE INDEX idx_entity_normalized_name ON entity (normalized_name);
CREATE INDEX idx_entity_scope_status_depth ON entity (in_scope, entry_status, depth_tier);
CREATE INDEX idx_entity_type ON entity (type);

CREATE TABLE entity_alias (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    entity_id BIGINT NOT NULL REFERENCES entity(id) ON DELETE CASCADE,
    alias TEXT NOT NULL,
    normalized_alias TEXT NOT NULL,
    language_code TEXT,
    source_passage_id BIGINT REFERENCES passage(id) ON DELETE SET NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT uq_entity_alias_normalized UNIQUE (entity_id, normalized_alias)
);

CREATE INDEX idx_entity_alias_normalized ON entity_alias (normalized_alias);
CREATE INDEX idx_entity_alias_trgm ON entity_alias USING GIN (alias gin_trgm_ops);

CREATE TABLE entity_external_id (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    entity_id BIGINT NOT NULL REFERENCES entity(id) ON DELETE CASCADE,
    provider TEXT NOT NULL,
    external_id TEXT NOT NULL,
    url TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT uq_entity_external_provider_id UNIQUE (provider, external_id),
    CONSTRAINT uq_entity_provider UNIQUE (entity_id, provider)
);

CREATE TABLE place_profile (
    entity_id BIGINT PRIMARY KEY REFERENCES entity(id) ON DELETE CASCADE,
    address TEXT,
    ward TEXT,
    district TEXT,
    province TEXT,
    latitude NUMERIC(9, 6),
    longitude NUMERIC(9, 6),
    primary_passage_id BIGINT REFERENCES passage(id) ON DELETE SET NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT chk_place_profile_latitude CHECK (
        latitude IS NULL OR latitude BETWEEN -90 AND 90
    ),
    CONSTRAINT chk_place_profile_longitude CHECK (
        longitude IS NULL OR longitude BETWEEN -180 AND 180
    )
);

-- CLAIM
CREATE TABLE claim_field (
    code TEXT PRIMARY KEY,
    label_vi TEXT NOT NULL,
    label_en TEXT,
    value_type TEXT NOT NULL DEFAULT 'text',
    default_unit TEXT,
    is_time_sensitive BOOLEAN NOT NULL DEFAULT false
);

CREATE TABLE claim (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    entity_id BIGINT NOT NULL REFERENCES entity(id) ON DELETE CASCADE,
    field_code TEXT NOT NULL REFERENCES claim_field(code),
    value JSONB NOT NULL,
    status TEXT NOT NULL DEFAULT 'proposed',
    confidence NUMERIC(4, 3),
    note TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT chk_claim_status CHECK (
        status IN ('proposed', 'accepted', 'disputed', 'rejected', 'superseded')
    ),
    CONSTRAINT chk_claim_confidence CHECK (
        confidence IS NULL OR confidence BETWEEN 0 AND 1
    )
);

CREATE INDEX idx_claim_entity_field ON claim (entity_id, field_code);
CREATE INDEX idx_claim_value_gin ON claim USING GIN (value);

-- RELATION
CREATE TABLE predicate (
    code TEXT PRIMARY KEY,
    label_vi TEXT NOT NULL,
    label_en TEXT,
    inverse_of TEXT REFERENCES predicate(code),
    is_symmetric BOOLEAN NOT NULL DEFAULT false
);

CREATE TABLE relation (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    subject_id BIGINT NOT NULL REFERENCES entity(id) ON DELETE CASCADE,
    predicate TEXT NOT NULL REFERENCES predicate(code),
    object_id BIGINT NOT NULL REFERENCES entity(id) ON DELETE CASCADE,
    status TEXT NOT NULL DEFAULT 'proposed',
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT chk_relation_no_loop CHECK (subject_id <> object_id),
    CONSTRAINT chk_relation_status CHECK (
        status IN ('proposed', 'accepted', 'disputed', 'rejected', 'superseded')
    )
);

CREATE INDEX idx_relation_subject ON relation (subject_id, predicate);
CREATE INDEX idx_relation_object ON relation (object_id, predicate);

-- TIMELINE
CREATE TABLE event_type (
    code TEXT PRIMARY KEY,
    label_vi TEXT NOT NULL,
    label_en TEXT
);

CREATE TABLE timeline_event (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    entity_id BIGINT NOT NULL REFERENCES entity(id) ON DELETE CASCADE,
    year_start INT NOT NULL,
    year_end INT,
    "precision" TEXT NOT NULL DEFAULT 'year',
    event_type TEXT NOT NULL REFERENCES event_type(code),
    title TEXT NOT NULL,
    summary TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT chk_timeline_year_range CHECK (
        year_end IS NULL OR year_end >= year_start
    ),
    CONSTRAINT chk_timeline_precision CHECK (
        "precision" IN ('year', 'decade', 'century', 'range', 'circa')
    )
);

CREATE INDEX idx_timeline_entity_year ON timeline_event (entity_id, year_start);

CREATE TABLE participant_role (
    code TEXT PRIMARY KEY,
    label_vi TEXT NOT NULL,
    label_en TEXT
);

CREATE TABLE timeline_event_participant (
    timeline_event_id BIGINT NOT NULL REFERENCES timeline_event(id) ON DELETE CASCADE,
    entity_id BIGINT NOT NULL REFERENCES entity(id) ON DELETE CASCADE,
    role_code TEXT NOT NULL REFERENCES participant_role(code),
    PRIMARY KEY (timeline_event_id, entity_id, role_code)
);

CREATE INDEX idx_timeline_participant_entity
    ON timeline_event_participant (entity_id, role_code);

-- NARRATIVE
CREATE TABLE narrative_section (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    entity_id BIGINT NOT NULL REFERENCES entity(id) ON DELETE CASCADE,
    section_code TEXT NOT NULL,
    title TEXT NOT NULL,
    body_md TEXT NOT NULL,
    language_code TEXT NOT NULL DEFAULT 'vi',
    order_index INT NOT NULL DEFAULT 0,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT chk_narrative_section_code CHECK (
        section_code IN (
            'tong_quan', 'ten_goi', 'khoi_lap', 'vai_tro_lich_su',
            'kien_truc', 'hien_vat', 'nhan_vat', 'bien_dong_hien_dai',
            'tham_quan'
        )
    ),
    CONSTRAINT uq_narrative_section UNIQUE (entity_id, section_code, language_code)
);

CREATE INDEX idx_narrative_entity ON narrative_section (entity_id, order_index);

-- HERITAGE / 3D TOUR
CREATE TABLE language (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code TEXT NOT NULL UNIQUE,
    name TEXT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);


CREATE TABLE heritage (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    set_id BIGINT REFERENCES heritage_set(id) ON DELETE SET NULL,
    slug TEXT NOT NULL UNIQUE,
    title TEXT NOT NULL,
    tagline TEXT,
    description TEXT,
    region TEXT,
    lat DOUBLE PRECISION,
    lng DOUBLE PRECISION,
    duration_seconds INT,
    launch_date DATE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT chk_heritage_lat CHECK (lat IS NULL OR lat BETWEEN -90 AND 90),
    CONSTRAINT chk_heritage_lng CHECK (lng IS NULL OR lng BETWEEN -180 AND 180),
    CONSTRAINT chk_heritage_duration CHECK (duration_seconds IS NULL OR duration_seconds >= 0)
);


CREATE TABLE sky_preset (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL UNIQUE,
    turbidity DOUBLE PRECISION,
    rayleigh DOUBLE PRECISION,
    elevation DOUBLE PRECISION,
    azimuth DOUBLE PRECISION,
    exposure DOUBLE PRECISION,
    light_settings JSONB,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE scene (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    heritage_id BIGINT NOT NULL REFERENCES heritage(id) ON DELETE CASCADE,
    sequence INT NOT NULL,
    title TEXT NOT NULL,
    description TEXT,
    sky_preset_id BIGINT REFERENCES sky_preset(id) ON DELETE SET NULL,
    -- Camera nằm trong GLB (NULL = dùng camera mặc định của GLB)
    camera_node_name TEXT,
    -- Hoặc khai báo camera trực tiếp trong DB
    cam_start_pos JSONB,
    cam_start_target JSONB,
    cam_zoom_pos JSONB,
    cam_zoom_target JSONB,
    instant_move BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT uq_scene_heritage_sequence UNIQUE (heritage_id, sequence),
    CONSTRAINT chk_scene_sequence CHECK (sequence >= 0)
);

CREATE INDEX idx_scene_heritage_sequence ON scene (heritage_id, sequence);

CREATE TABLE model_asset (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    scene_id BIGINT NOT NULL REFERENCES scene(id) ON DELETE CASCADE,
    file_url TEXT NOT NULL,
    format TEXT NOT NULL DEFAULT 'glb',
    lod_level INT NOT NULL DEFAULT 0,
    compression TEXT,
    file_size_bytes BIGINT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT chk_model_asset_format CHECK (format IN ('glb', 'splat', 'sog')),
    CONSTRAINT chk_model_asset_lod CHECK (lod_level >= 0),
    CONSTRAINT chk_model_asset_compression CHECK (
        compression IS NULL
        OR compression IN ('draco', 'ktx2', 'meshopt', 'draco+ktx2', 'none')
    ),
    CONSTRAINT chk_model_asset_file_size CHECK (
        file_size_bytes IS NULL OR file_size_bytes >= 0
    ),
    CONSTRAINT uq_model_asset_scene_lod UNIQUE (scene_id, lod_level)
);

CREATE INDEX idx_model_asset_scene ON model_asset (scene_id);

CREATE TABLE voice (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    title TEXT,
    bio TEXT,
    headshot_url TEXT,
    intro_video_url TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE voice_clip (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    voice_id BIGINT NOT NULL REFERENCES voice(id) ON DELETE CASCADE,
    scene_id BIGINT NOT NULL REFERENCES scene(id) ON DELETE CASCADE,
    video_url TEXT,
    audio_url TEXT,
    bubble_text TEXT,
    sort_order INT NOT NULL DEFAULT 0,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT chk_voice_clip_sort_order CHECK (sort_order >= 0)
);

CREATE INDEX idx_voice_clip_scene_order ON voice_clip (scene_id, sort_order);
CREATE INDEX idx_voice_clip_voice ON voice_clip (voice_id);

CREATE TABLE media_item (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    scene_id BIGINT NOT NULL REFERENCES scene(id) ON DELETE CASCADE,
    type TEXT NOT NULL,
    title TEXT,
    caption TEXT,
    asset_url TEXT NOT NULL,
    thumb_url TEXT,
    credit TEXT,
    sort_order INT NOT NULL DEFAULT 0,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT chk_media_item_type CHECK (
        type IN ('image', 'video', 'audio', 'model', 'document', 'other')
    ),
    CONSTRAINT chk_media_item_sort_order CHECK (sort_order >= 0)
);

CREATE INDEX idx_media_item_scene_order ON media_item (scene_id, sort_order);

CREATE TABLE interactive (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    scene_id BIGINT NOT NULL REFERENCES scene(id) ON DELETE CASCADE,
    mode TEXT NOT NULL,
    cam_pos JSONB,
    cam_target JSONB,
    explore_area JSONB,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT uq_interactive_scene_mode UNIQUE (scene_id, mode)
);

CREATE INDEX idx_interactive_scene ON interactive (scene_id);

CREATE TABLE interactive_highlight (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    interactive_id BIGINT NOT NULL REFERENCES interactive(id) ON DELETE CASCADE,
    popup_title TEXT,
    popup_text TEXT,
    media_url TEXT,
    cam_pos JSONB,
    cam_target JSONB,
    lens_pos JSONB,
    lens_rot JSONB,
    lens_scale JSONB,
    sort_order INT NOT NULL DEFAULT 0,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT chk_interactive_highlight_sort_order CHECK (sort_order >= 0)
);

CREATE INDEX idx_interactive_highlight_order
    ON interactive_highlight (interactive_id, sort_order);

CREATE TABLE scene_highlight (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    scene_id BIGINT NOT NULL REFERENCES scene(id) ON DELETE CASCADE,
    model_url TEXT NOT NULL,
    position JSONB NOT NULL,
    rotation JSONB NOT NULL,
    scale JSONB NOT NULL,
    animation_type TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX idx_scene_highlight_scene ON scene_highlight (scene_id);



CREATE TABLE link (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    heritage_id BIGINT NOT NULL REFERENCES heritage(id) ON DELETE CASCADE,
    language_id BIGINT REFERENCES language(id) ON DELETE SET NULL,
    title TEXT NOT NULL,
    url TEXT NOT NULL,
    link_type TEXT,
    sort_order INT NOT NULL DEFAULT 0,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT chk_link_sort_order CHECK (sort_order >= 0)
);

CREATE INDEX idx_link_heritage_order ON link (heritage_id, sort_order);

-- =====================================================================
-- CHAT
-- =====================================================================
CREATE TABLE chat_session (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ip_hash TEXT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX idx_chat_session_created ON chat_session (created_at DESC);

CREATE TABLE chat_message (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_id BIGINT NOT NULL REFERENCES chat_session(id) ON DELETE CASCADE,
    role TEXT NOT NULL,
    content TEXT NOT NULL,
    citations JSONB NOT NULL DEFAULT '[]'::jsonb,
    response_status TEXT,
    abstained BOOLEAN NOT NULL DEFAULT false,
    retrieval_strategy TEXT,
    latency_ms INT,
    model TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT chk_chat_message_role CHECK (role IN ('user', 'assistant')),
    CONSTRAINT chk_chat_message_citations_array CHECK (jsonb_typeof(citations) = 'array'),
    CONSTRAINT chk_chat_message_response CHECK (
        (
            role = 'user'
            AND response_status IS NULL
            AND abstained = false
        )
        OR (
            role = 'assistant'
            AND response_status IN ('answered', 'clarify', 'abstained')
            AND abstained = (response_status = 'abstained')
        )
    ),
    CONSTRAINT chk_chat_message_latency CHECK (latency_ms IS NULL OR latency_ms >= 0)
);

CREATE INDEX idx_chat_message_session ON chat_message (session_id, created_at);

CREATE TABLE chat_feedback (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    message_id BIGINT NOT NULL REFERENCES chat_message(id) ON DELETE CASCADE,
    rating SMALLINT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT chk_chat_feedback_rating CHECK (rating IN (-1, 1))
);

CREATE INDEX idx_chat_feedback_message ON chat_feedback (message_id);

-- SEED DATA
INSERT INTO claim_field (code, label_vi, value_type, default_unit, is_time_sensitive)
VALUES
    ('construction_year', 'Năm xây dựng / khởi lập', 'year',   NULL, false),
    ('completion_year',   'Năm hoàn thành',          'year',   NULL, false),
    ('height',            'Chiều cao',               'number', 'm',  false),
    ('address',           'Địa chỉ',                 'text',   NULL, true),
    ('description',       'Mô tả',                   'text',   NULL, false);

INSERT INTO event_type (code, label_vi, label_en)
VALUES
    ('establishment', 'Khởi lập',          'Establishment'),
    ('construction',  'Xây dựng',          'Construction'),
    ('restoration',   'Trùng tu',          'Restoration'),
    ('renovation',    'Tu sửa',            'Renovation'),
    ('historical',    'Sự kiện lịch sử',   'Historical Event'),
    ('political',     'Sự kiện chính trị', 'Political Event'),
    ('religious',     'Sự kiện tôn giáo',  'Religious Event'),
    ('cultural',      'Sự kiện văn hóa',   'Cultural Event'),
    ('other',         'Khác',              'Other');

INSERT INTO predicate (code, label_vi, label_en, is_symmetric)
VALUES
    ('founded',         'khởi lập',          'founded',         false),
    ('located_in',      'nằm tại',           'located in',      false),
    ('built_by',        'được xây dựng bởi', 'built by',        false),
    ('restored_by',     'được trùng tu bởi', 'restored by',     false),
    ('designed_by',     'được thiết kế bởi', 'designed by',     false),
    ('associated_with', 'liên quan đến',     'associated with', true),
    ('part_of',         'thuộc về',          'part of',         false),
    ('contains',        'chứa',              'contains',        false),
    ('commemorates',    'tưởng niệm',        'commemorates',    false);