services:
  migrate:
    image: ${BACKEND_IMAGE:?BACKEND_IMAGE is required}
    build: !reset null
  import-data:
    image: ${BACKEND_IMAGE:?BACKEND_IMAGE is required}
    build: !reset null
  backend:
    image: ${BACKEND_IMAGE:?BACKEND_IMAGE is required}
    build: !reset null
    environment:
      RELEASE_REVISION: ${RELEASE_REVISION:?RELEASE_REVISION is required}
  frontend:
    image: ${FRONTEND_IMAGE:?FRONTEND_IMAGE is required}
    build: !reset null
